[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_src_filter =
    +<*>
    -<selftest_dht/*>
monitor_speed = 115200
upload_port = COM3
upload_speed = 921600
board_build.partitions = partitions/ota.csv
platform_packages =
    platformio/framework-arduinoespressif32@3.20017.0
build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=3
lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    crankyoldgit/IRremoteESP8266@^2.8.6
    bblanchon/ArduinoJson@^7.2.1
    knolleary/PubSubClient@^2.8.0

[env:native]
platform = native
build_flags = -std=c++17
lib_deps =
    bblanchon/ArduinoJson@^7.2.1

[env:dht-selftest]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_src_filter = +<selftest_dht/*>
monitor_speed = 115200
upload_port = COM3
upload_speed = 921600
platform_packages =
    platformio/framework-arduinoespressif32@3.20017.0
lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
